CREATE DATABASE Temp;

USE Temp;

CREATE TABLE User (
    id INTEGER AUTO_INCREMENT,
    name VARCHAR(16) UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE Hello (
    id INTEGER AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    message VARCHAR(16) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(id) REFERENCES User(id)
);


INSERT INTO Hello(message) VALUES("Hello World!");

SELECT message FROM Hello;


DROP DATABASE Temp;
